package me.tud.mc2d.generators;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.TypeSpec;

import javax.annotation.processing.Generated;

public record GeneratedType(Class<? extends Generator<?>> generator, String packageName, TypeSpec type) {

    public GeneratedType {
        type = type.toBuilder()
                .addJavadoc("This class contains autogenerated code. Please do <b>NOT</b> edit manually.")
                .addAnnotation(AnnotationSpec.builder(Generated.class).addMember("value", "$S", generator.getName()).build())
                .build();
    }

    public static GeneratedType[] of(Class<? extends Generator<?>> generator, String packageName, TypeSpec[] types) {
        GeneratedType[] generatedTypes = new GeneratedType[types.length];
        for (int i = 0; i < types.length; i++)
            generatedTypes[i] = new GeneratedType(generator, packageName, types[i]);
        return generatedTypes;
    }

}
