package me.tud.mc2d.generators;

import com.google.gson.stream.JsonReader;
import com.palantir.javapoet.*;
import me.tud.mc2d.generators.util.Imports;
import me.tud.mc2d.generators.util.StringUtils;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.*;

public class PacketsGenerator extends JsonFileGenerator {

    private static final String RESOURCE_LOCATION = "/packets.json";

    private static final ClassName CLASS_NAME = ClassName.get("me.tud.mc2d.network.packets", "Packets");
    private static final ClassName PACKET_INFO_CLASS = ClassName.get("me.tud.mc2d.network.packets", "Packet", "Info");
    private static final ClassName CONNECTION_STATE_CLASS = ClassName.get("me.tud.mc2d.network", "ConnectionState");
    private static final ClassName PACKET_DIRECTION_CLASS = ClassName.get("me.tud.mc2d.network.packets", "Packet", "Direction");

    public static void main(String[] args) throws Exception {
        new PacketsGenerator().run(args);
    }

    public PacketsGenerator() {
        super(CLASS_NAME, RESOURCE_LOCATION);
    }

    @Override
    public TypeSpec generate(JsonReader reader) throws IOException {
        TypeSpec.Builder packetIDsType = TypeSpec.classBuilder(CLASS_NAME)
                .addJavadoc("An autogenerated class containing all packet information. Do <b>NOT</b> edit manually.")
                .addAnnotation(generatedAnnotation())
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addMethod(PRIVATE_CONSTRUCTOR);
        reader.beginObject();
        while (reader.hasNext())
            packetIDsType.addType(generateStateClass(reader));
        reader.endObject();
        return packetIDsType.build();
    }

    private TypeSpec generateStateClass(JsonReader reader) throws IOException {
        String state = reader.nextName();
        TypeSpec.Builder stateType = TypeSpec.classBuilder(StringUtils.capitalize(state))
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .addMethod(PRIVATE_CONSTRUCTOR);
        reader.beginObject();
        while (reader.hasNext())
            stateType.addType(generateDirectionClass(state, reader));
        reader.endObject();
        return stateType.build();
    }

    private TypeSpec generateDirectionClass(String state, JsonReader reader) throws IOException {
        String direction = reader.nextName();
        TypeSpec.Builder directionType = TypeSpec.classBuilder(StringUtils.capitalize(direction))
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .addMethod(PRIVATE_CONSTRUCTOR);
        List<Map.Entry<String, Integer>> packets = new ArrayList<>();
        reader.beginObject();
        while (reader.hasNext()) {
            String resource = reader.nextName();
            reader.beginObject();
            reader.skipValue();
            int id = reader.nextInt();
            reader.endObject();
            packets.add(Map.entry(resource, id));
        }
        reader.endObject();

        packets.sort(Comparator.comparingInt(Map.Entry::getValue));
        for (Map.Entry<String, Integer> packet : packets) {
            String fieldName = packet.getKey()
                    .substring("minecraft:".length())
                    .replaceAll("[^A-Za-z0-9_]", "_")
                    .toUpperCase(Locale.ENGLISH);
            directionType.addField(FieldSpec.builder(PACKET_INFO_CLASS, fieldName)
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                    .initializer(
                            "new $T($T.parse($S), $L, $T.$L, $T.$L)",
                            PACKET_INFO_CLASS,
                            Imports.NAMESPACED_KEY, packet.getKey(),
                            String.format("0x%02X", packet.getValue()),
                            CONNECTION_STATE_CLASS, state.toUpperCase(Locale.ENGLISH),
                            PACKET_DIRECTION_CLASS, direction.toUpperCase(Locale.ENGLISH)
                    )
                    .build());
        }
        return directionType.build();
    }

}
