package me.tud.mc2d.generators;

import com.google.gson.stream.JsonReader;
import com.palantir.javapoet.*;

import javax.annotation.processing.Generated;
import javax.lang.model.element.Modifier;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.*;

public class PacketsGenerator {

    private static final String PACKAGE = "me.tud.mc2d.generated";
    private static final String CLASS_NAME = "Packets";
    private static final String RESOURCE_LOCATION = "/packets.json";

    private static final ClassName PACKET_INFO_CLASS = ClassName.get("me.tud.mc2d.network.packets", "Packet", "Info");
    private static final ClassName NAMESPACED_KEY_CLASS = ClassName.get("me.tud.mc2d.util", "NamespacedKey");
    private static final ClassName CONNECTION_STATE_CLASS = ClassName.get("me.tud.mc2d.network", "ConnectionState");
    private static final ClassName PACKET_DIRECTION_CLASS = ClassName.get("me.tud.mc2d.network.packets", "Packet", "Direction");

    private static final MethodSpec PRIVATE_CONSTRUCTOR = MethodSpec.constructorBuilder()
            .addModifiers(Modifier.PRIVATE)
            .build();

    public static void main(String[] args) throws IOException {
        File out = null;

        for (int i = 0; i < args.length; i++) {
            if (args[i].equals("--output") && i + 1 < args.length)
                out = new File(args[++i]);
        }

        if (out == null)
            throw new IllegalArgumentException("Missing --output <dir>");

        run(out);
    }

    public static void run(File outputDir) throws IOException {
        InputStream in = PacketsGenerator.class.getResourceAsStream(RESOURCE_LOCATION);
        if (in == null)
            throw new IOException("Resource not found: " + RESOURCE_LOCATION);
        JavaFile output = readJsonStream(in);
        output.writeTo(outputDir);
    }

    private static JavaFile readJsonStream(InputStream in) throws IOException {
        try (JsonReader reader = new JsonReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
            return JavaFile.builder(PACKAGE, generateClass(reader))
                    .indent("    ")
                    .build();
        }
    }

    private static TypeSpec generateClass(JsonReader reader) throws IOException {
        TypeSpec.Builder packetIDsType = TypeSpec.classBuilder(CLASS_NAME)
                .addJavadoc("An autogenerated class containing all packet information. Do <b>NOT</b> edit manually.")
                .addAnnotation(AnnotationSpec.builder(Generated.class)
                        .addMember("value", "$S", PacketsGenerator.class.getName())
                        .addMember("date", "$S", Instant.now().toString())
                        .build())
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addMethod(PRIVATE_CONSTRUCTOR);
        reader.beginObject();
        while (reader.hasNext())
            packetIDsType.addType(generateStateClass(reader));
        reader.endObject();
        return packetIDsType.build();
    }

    private static TypeSpec generateStateClass(JsonReader reader) throws IOException {
        String state = reader.nextName();
        TypeSpec.Builder stateType = TypeSpec.classBuilder(capitalize(state))
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .addMethod(PRIVATE_CONSTRUCTOR);
        reader.beginObject();
        while (reader.hasNext())
            stateType.addType(generateDirectionClass(state, reader));
        reader.endObject();
        return stateType.build();
    }

    private static TypeSpec generateDirectionClass(String state, JsonReader reader) throws IOException {
        String direction = reader.nextName();
        TypeSpec.Builder directionType = TypeSpec.classBuilder(capitalize(direction))
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .addMethod(PRIVATE_CONSTRUCTOR);
        List<Map.Entry<String, Integer>> packets = new ArrayList<>();
        reader.beginObject();
        while (reader.hasNext()) {
            String resource = reader.nextName();
            reader.beginObject();
            reader.skipValue();
            int id = reader.nextInt();
            reader.endObject();
            packets.add(Map.entry(resource, id));
        }
        reader.endObject();

        packets.sort(Comparator.comparingInt(Map.Entry::getValue));
        for (Map.Entry<String, Integer> packet : packets) {
            String fieldName = packet.getKey()
                    .substring("minecraft:".length())
                    .replaceAll("[^A-Za-z0-9_]", "_")
                    .toUpperCase(Locale.ENGLISH);
            directionType.addField(FieldSpec.builder(PACKET_INFO_CLASS, fieldName)
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                    .initializer(
                            "new $T($T.parse($S), $L, $T.$L, $T.$L)",
                            PACKET_INFO_CLASS,
                            NAMESPACED_KEY_CLASS, packet.getKey(),
                            String.format("0x%02X", packet.getValue()),
                            CONNECTION_STATE_CLASS, state.toUpperCase(Locale.ENGLISH),
                            PACKET_DIRECTION_CLASS, direction.toUpperCase(Locale.ENGLISH)
                    )
                    .build());
        }
        return directionType.build();
    }

    private static String capitalize(String input) {
        if (input == null || input.isBlank())
            return input;
        return Character.toUpperCase(input.charAt(0)) + input.substring(1);
    }

}
